parameters:
#    clw_cover_letter.example.class: CLW\Bundle\CoverLetterBundle\Example

services:
#    clw_cover_letter.example:
#        class: %clw_cover_letter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
